# coding: utf-8

# flake8: noqa
"""
Notifications API

API for notification delivery system

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from crypticorn.notification.client.models.broadcast import Broadcast
    from crypticorn.notification.client.models.broadcast_create import BroadcastCreate
    from crypticorn.notification.client.models.broadcast_update import BroadcastUpdate
    from crypticorn.notification.client.models.dashboard_action_button import (
        DashboardActionButton,
    )
    from crypticorn.notification.client.models.dashboard_field import DashboardField
    from crypticorn.notification.client.models.dashboard_notification import (
        DashboardNotification,
    )
    from crypticorn.notification.client.models.dashboard_notification_update import (
        DashboardNotificationUpdate,
    )
    from crypticorn.notification.client.models.exception_detail_literal_unknown_error_invalid_data_request_invalid_data_response_object_already_exists_object_not_found_template_not_found_invalid_template_variables import (
        ExceptionDetailLiteralUnknownErrorInvalidDataRequestInvalidDataResponseObjectAlreadyExistsObjectNotFoundTemplateNotFoundInvalidTemplateVariables,
    )
    from crypticorn.notification.client.models.notification_create import (
        NotificationCreate,
    )
    from crypticorn.notification.client.models.paginated_response_dashboard_notification import (
        PaginatedResponseDashboardNotification,
    )
    from crypticorn.notification.client.models.template import Template
    from crypticorn.notification.client.models.ui_template import UITemplate
    from crypticorn.notification.client.models.user_setting import UserSetting
    from crypticorn.notification.client.models.user_setting_create import (
        UserSettingCreate,
    )
    from crypticorn.notification.client.models.user_setting_update import (
        UserSettingUpdate,
    )

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from crypticorn.notification.client.models.broadcast import Broadcast
from crypticorn.notification.client.models.broadcast_create import BroadcastCreate
from crypticorn.notification.client.models.broadcast_update import BroadcastUpdate
from crypticorn.notification.client.models.dashboard_action_button import DashboardActionButton
from crypticorn.notification.client.models.dashboard_field import DashboardField
from crypticorn.notification.client.models.dashboard_notification import DashboardNotification
from crypticorn.notification.client.models.dashboard_notification_update import DashboardNotificationUpdate
from crypticorn.notification.client.models.exception_detail_literal_unknown_error_invalid_data_request_invalid_data_response_object_already_exists_object_not_found_template_not_found_invalid_template_variables import ExceptionDetailLiteralUnknownErrorInvalidDataRequestInvalidDataResponseObjectAlreadyExistsObjectNotFoundTemplateNotFoundInvalidTemplateVariables
from crypticorn.notification.client.models.notification_create import NotificationCreate
from crypticorn.notification.client.models.paginated_response_dashboard_notification import PaginatedResponseDashboardNotification
from crypticorn.notification.client.models.template import Template
from crypticorn.notification.client.models.ui_template import UITemplate
from crypticorn.notification.client.models.user_setting import UserSetting
from crypticorn.notification.client.models.user_setting_create import UserSettingCreate
from crypticorn.notification.client.models.user_setting_update import UserSettingUpdate

""",
            name=__name__,
            doc=__doc__,
        )
    )
