# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HolderInfo(BaseModel):
    """
    HolderInfo
    """ # noqa: E501
    rank: Optional[StrictInt] = 0
    address: Optional[StrictStr] = ''
    amount: Optional[StrictStr] = ''
    amount_usd: Optional[StrictStr] = ''
    amount_percentage: Optional[StrictStr] = ''
    cost: Optional[StrictStr] = ''
    cost_rate: Optional[StrictStr] = ''
    holding_time: Optional[StrictInt] = 0
    realized_profit: Optional[StrictStr] = ''
    unrealized_profit: Optional[StrictStr] = ''
    pnl: Optional[StrictStr] = ''
    tags: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["rank", "address", "amount", "amount_usd", "amount_percentage", "cost", "cost_rate", "holding_time", "realized_profit", "unrealized_profit", "pnl", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HolderInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HolderInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rank": obj.get("rank") if obj.get("rank") is not None else 0,
            "address": obj.get("address") if obj.get("address") is not None else '',
            "amount": obj.get("amount") if obj.get("amount") is not None else '',
            "amount_usd": obj.get("amount_usd") if obj.get("amount_usd") is not None else '',
            "amount_percentage": obj.get("amount_percentage") if obj.get("amount_percentage") is not None else '',
            "cost": obj.get("cost") if obj.get("cost") is not None else '',
            "cost_rate": obj.get("cost_rate") if obj.get("cost_rate") is not None else '',
            "holding_time": obj.get("holding_time") if obj.get("holding_time") is not None else 0,
            "realized_profit": obj.get("realized_profit") if obj.get("realized_profit") is not None else '',
            "unrealized_profit": obj.get("unrealized_profit") if obj.get("unrealized_profit") is not None else '',
            "pnl": obj.get("pnl") if obj.get("pnl") is not None else '',
            "tags": obj.get("tags")
        })
        return _obj


