# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HolderComposition(BaseModel):
    """
    HolderComposition
    """ # noqa: E501
    smart_degen_count: Optional[StrictInt] = 0
    renowned_count: Optional[StrictInt] = 0
    fresh_wallet_count: Optional[StrictInt] = 0
    dex_bot_count: Optional[StrictInt] = 0
    insider_count: Optional[StrictInt] = 0
    following_count: Optional[StrictInt] = 0
    dev_count: Optional[StrictInt] = 0
    bluechip_owner_count: Optional[StrictInt] = 0
    bundler_count: Optional[StrictInt] = 0
    sniper_count: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["smart_degen_count", "renowned_count", "fresh_wallet_count", "dex_bot_count", "insider_count", "following_count", "dev_count", "bluechip_owner_count", "bundler_count", "sniper_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HolderComposition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HolderComposition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "smart_degen_count": obj.get("smart_degen_count") if obj.get("smart_degen_count") is not None else 0,
            "renowned_count": obj.get("renowned_count") if obj.get("renowned_count") is not None else 0,
            "fresh_wallet_count": obj.get("fresh_wallet_count") if obj.get("fresh_wallet_count") is not None else 0,
            "dex_bot_count": obj.get("dex_bot_count") if obj.get("dex_bot_count") is not None else 0,
            "insider_count": obj.get("insider_count") if obj.get("insider_count") is not None else 0,
            "following_count": obj.get("following_count") if obj.get("following_count") is not None else 0,
            "dev_count": obj.get("dev_count") if obj.get("dev_count") is not None else 0,
            "bluechip_owner_count": obj.get("bluechip_owner_count") if obj.get("bluechip_owner_count") is not None else 0,
            "bundler_count": obj.get("bundler_count") if obj.get("bundler_count") is not None else 0,
            "sniper_count": obj.get("sniper_count") if obj.get("sniper_count") is not None else 0
        })
        return _obj


