# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IntelAggregateStats(BaseModel):
    """
    Aggregate metrics derived from token intelligence data.
    """ # noqa: E501
    tokens_with_intel: Optional[StrictInt] = Field(default=0, description="Number of tokens with intel data")
    avg_holder_count: Optional[Union[StrictFloat, StrictInt]] = None
    avg_top10_holder_rate: Optional[Union[StrictFloat, StrictInt]] = None
    avg_rug_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    smart_money_token_count: Optional[StrictInt] = Field(default=0, description="Tokens with at least one smart money wallet")
    avg_fresh_wallet_rate: Optional[Union[StrictFloat, StrictInt]] = None
    avg_insider_count: Optional[Union[StrictFloat, StrictInt]] = None
    renounced_mint_pct: Optional[Union[StrictFloat, StrictInt]] = None
    honeypot_pct: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["tokens_with_intel", "avg_holder_count", "avg_top10_holder_rate", "avg_rug_ratio", "smart_money_token_count", "avg_fresh_wallet_rate", "avg_insider_count", "renounced_mint_pct", "honeypot_pct"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntelAggregateStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if avg_holder_count (nullable) is None
        # and model_fields_set contains the field
        if self.avg_holder_count is None and "avg_holder_count" in self.model_fields_set:
            _dict['avg_holder_count'] = None

        # set to None if avg_top10_holder_rate (nullable) is None
        # and model_fields_set contains the field
        if self.avg_top10_holder_rate is None and "avg_top10_holder_rate" in self.model_fields_set:
            _dict['avg_top10_holder_rate'] = None

        # set to None if avg_rug_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.avg_rug_ratio is None and "avg_rug_ratio" in self.model_fields_set:
            _dict['avg_rug_ratio'] = None

        # set to None if avg_fresh_wallet_rate (nullable) is None
        # and model_fields_set contains the field
        if self.avg_fresh_wallet_rate is None and "avg_fresh_wallet_rate" in self.model_fields_set:
            _dict['avg_fresh_wallet_rate'] = None

        # set to None if avg_insider_count (nullable) is None
        # and model_fields_set contains the field
        if self.avg_insider_count is None and "avg_insider_count" in self.model_fields_set:
            _dict['avg_insider_count'] = None

        # set to None if renounced_mint_pct (nullable) is None
        # and model_fields_set contains the field
        if self.renounced_mint_pct is None and "renounced_mint_pct" in self.model_fields_set:
            _dict['renounced_mint_pct'] = None

        # set to None if honeypot_pct (nullable) is None
        # and model_fields_set contains the field
        if self.honeypot_pct is None and "honeypot_pct" in self.model_fields_set:
            _dict['honeypot_pct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntelAggregateStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tokens_with_intel": obj.get("tokens_with_intel") if obj.get("tokens_with_intel") is not None else 0,
            "avg_holder_count": obj.get("avg_holder_count"),
            "avg_top10_holder_rate": obj.get("avg_top10_holder_rate"),
            "avg_rug_ratio": obj.get("avg_rug_ratio"),
            "smart_money_token_count": obj.get("smart_money_token_count") if obj.get("smart_money_token_count") is not None else 0,
            "avg_fresh_wallet_rate": obj.get("avg_fresh_wallet_rate"),
            "avg_insider_count": obj.get("avg_insider_count"),
            "renounced_mint_pct": obj.get("renounced_mint_pct"),
            "honeypot_pct": obj.get("honeypot_pct")
        })
        return _obj


