# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class KolInfo(BaseModel):
    """
    KolInfo
    """ # noqa: E501
    author_id: Optional[StrictStr] = ''
    handle: Optional[StrictStr] = ''
    nickname: Optional[StrictStr] = ''
    avatar: Optional[StrictStr] = ''
    followers: Optional[StrictInt] = 0
    mentions_count: Optional[StrictStr] = ''
    engagement_count: Optional[StrictStr] = ''
    impressions_count: Optional[StrictStr] = ''
    first_mention_time: Optional[StrictInt] = 0
    first_mention_market_cap: Optional[StrictStr] = ''
    first_mention_price: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["author_id", "handle", "nickname", "avatar", "followers", "mentions_count", "engagement_count", "impressions_count", "first_mention_time", "first_mention_market_cap", "first_mention_price"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KolInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KolInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "author_id": obj.get("author_id") if obj.get("author_id") is not None else '',
            "handle": obj.get("handle") if obj.get("handle") is not None else '',
            "nickname": obj.get("nickname") if obj.get("nickname") is not None else '',
            "avatar": obj.get("avatar") if obj.get("avatar") is not None else '',
            "followers": obj.get("followers") if obj.get("followers") is not None else 0,
            "mentions_count": obj.get("mentions_count") if obj.get("mentions_count") is not None else '',
            "engagement_count": obj.get("engagement_count") if obj.get("engagement_count") is not None else '',
            "impressions_count": obj.get("impressions_count") if obj.get("impressions_count") is not None else '',
            "first_mention_time": obj.get("first_mention_time") if obj.get("first_mention_time") is not None else 0,
            "first_mention_market_cap": obj.get("first_mention_market_cap") if obj.get("first_mention_market_cap") is not None else '',
            "first_mention_price": obj.get("first_mention_price") if obj.get("first_mention_price") is not None else ''
        })
        return _obj


