# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MigrationInfo(BaseModel):
    """
    MigrationInfo
    """ # noqa: E501
    link_address: Optional[StrictStr] = ''
    explorer_url: Optional[StrictStr] = ''
    geckoterminal_url: Optional[StrictStr] = ''
    twitter_username: Optional[StrictStr] = ''
    website: Optional[StrictStr] = ''
    telegram: Optional[StrictStr] = ''
    description: Optional[StrictStr] = ''
    verify_status: Optional[StrictInt] = 0
    rug_address: Optional[StrictStr] = ''
    rug_ratio: Optional[StrictStr] = ''
    holder_rugged_num: Optional[StrictInt] = 0
    holder_token_num: Optional[StrictInt] = 0
    vote_like: Optional[StrictInt] = 0
    vote_dislike: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["link_address", "explorer_url", "geckoterminal_url", "twitter_username", "website", "telegram", "description", "verify_status", "rug_address", "rug_ratio", "holder_rugged_num", "holder_token_num", "vote_like", "vote_dislike"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MigrationInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MigrationInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "link_address": obj.get("link_address") if obj.get("link_address") is not None else '',
            "explorer_url": obj.get("explorer_url") if obj.get("explorer_url") is not None else '',
            "geckoterminal_url": obj.get("geckoterminal_url") if obj.get("geckoterminal_url") is not None else '',
            "twitter_username": obj.get("twitter_username") if obj.get("twitter_username") is not None else '',
            "website": obj.get("website") if obj.get("website") is not None else '',
            "telegram": obj.get("telegram") if obj.get("telegram") is not None else '',
            "description": obj.get("description") if obj.get("description") is not None else '',
            "verify_status": obj.get("verify_status") if obj.get("verify_status") is not None else 0,
            "rug_address": obj.get("rug_address") if obj.get("rug_address") is not None else '',
            "rug_ratio": obj.get("rug_ratio") if obj.get("rug_ratio") is not None else '',
            "holder_rugged_num": obj.get("holder_rugged_num") if obj.get("holder_rugged_num") is not None else 0,
            "holder_token_num": obj.get("holder_token_num") if obj.get("holder_token_num") is not None else 0,
            "vote_like": obj.get("vote_like") if obj.get("vote_like") is not None else 0,
            "vote_dislike": obj.get("vote_dislike") if obj.get("vote_dislike") is not None else 0
        })
        return _obj


