# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NativeTransferInfo(BaseModel):
    """
    NativeTransferInfo
    """ # noqa: E501
    tx_hash: Optional[StrictStr] = ''
    from_address: Optional[StrictStr] = ''
    amount: Optional[StrictStr] = ''
    transfer_ts: Optional[StrictInt] = 0
    twitter_username: Optional[StrictStr] = ''
    nickname: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["tx_hash", "from_address", "amount", "transfer_ts", "twitter_username", "nickname"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NativeTransferInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NativeTransferInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tx_hash": obj.get("tx_hash") if obj.get("tx_hash") is not None else '',
            "from_address": obj.get("from_address") if obj.get("from_address") is not None else '',
            "amount": obj.get("amount") if obj.get("amount") is not None else '',
            "transfer_ts": obj.get("transfer_ts") if obj.get("transfer_ts") is not None else 0,
            "twitter_username": obj.get("twitter_username") if obj.get("twitter_username") is not None else '',
            "nickname": obj.get("nickname") if obj.get("nickname") is not None else ''
        })
        return _obj


