# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PoolFeeInfo(BaseModel):
    """
    PoolFeeInfo
    """ # noqa: E501
    address: Optional[StrictStr] = ''
    exchange: Optional[StrictStr] = ''
    liquidity: Optional[Union[StrictFloat, StrictInt]] = 0.0
    fee_ratio: Optional[Union[StrictFloat, StrictInt]] = 0.0
    is_dynamic_fee: Optional[StrictBool] = False
    pool_type: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["address", "exchange", "liquidity", "fee_ratio", "is_dynamic_fee", "pool_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoolFeeInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoolFeeInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address") if obj.get("address") is not None else '',
            "exchange": obj.get("exchange") if obj.get("exchange") is not None else '',
            "liquidity": obj.get("liquidity") if obj.get("liquidity") is not None else 0.0,
            "fee_ratio": obj.get("fee_ratio") if obj.get("fee_ratio") is not None else 0.0,
            "is_dynamic_fee": obj.get("is_dynamic_fee") if obj.get("is_dynamic_fee") is not None else False,
            "pool_type": obj.get("pool_type") if obj.get("pool_type") is not None else ''
        })
        return _obj


