# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RiskAnalysisInfo(BaseModel):
    """
    RiskAnalysisInfo
    """ # noqa: E501
    risk_level: Optional[StrictInt] = 0
    risk_control_level: Optional[StrictInt] = 0
    buy_taxes: Optional[StrictStr] = ''
    sell_taxes: Optional[StrictStr] = ''
    high_risk_num: Optional[StrictInt] = 0
    middle_risk_num: Optional[StrictInt] = 0
    low_risk_num: Optional[StrictInt] = 0
    swap_analysis: Optional[Dict[str, Any]] = None
    contract_analysis: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["risk_level", "risk_control_level", "buy_taxes", "sell_taxes", "high_risk_num", "middle_risk_num", "low_risk_num", "swap_analysis", "contract_analysis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAnalysisInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if swap_analysis (nullable) is None
        # and model_fields_set contains the field
        if self.swap_analysis is None and "swap_analysis" in self.model_fields_set:
            _dict['swap_analysis'] = None

        # set to None if contract_analysis (nullable) is None
        # and model_fields_set contains the field
        if self.contract_analysis is None and "contract_analysis" in self.model_fields_set:
            _dict['contract_analysis'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAnalysisInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "risk_level": obj.get("risk_level") if obj.get("risk_level") is not None else 0,
            "risk_control_level": obj.get("risk_control_level") if obj.get("risk_control_level") is not None else 0,
            "buy_taxes": obj.get("buy_taxes") if obj.get("buy_taxes") is not None else '',
            "sell_taxes": obj.get("sell_taxes") if obj.get("sell_taxes") is not None else '',
            "high_risk_num": obj.get("high_risk_num") if obj.get("high_risk_num") is not None else 0,
            "middle_risk_num": obj.get("middle_risk_num") if obj.get("middle_risk_num") is not None else 0,
            "low_risk_num": obj.get("low_risk_num") if obj.get("low_risk_num") is not None else 0,
            "swap_analysis": obj.get("swap_analysis"),
            "contract_analysis": obj.get("contract_analysis")
        })
        return _obj


