# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SecurityInfo(BaseModel):
    """
    SecurityInfo
    """ # noqa: E501
    is_show_alert: Optional[StrictBool] = False
    top_10_holder_rate: Optional[StrictStr] = ''
    renounced_mint: Optional[StrictBool] = False
    renounced_freeze_account: Optional[StrictBool] = False
    burn_ratio: Optional[StrictStr] = ''
    burn_status: Optional[StrictStr] = ''
    dev_token_burn_amount: Optional[StrictStr] = ''
    dev_token_burn_ratio: Optional[StrictStr] = ''
    open_source: Optional[StrictInt] = 0
    blacklist: Optional[StrictInt] = 0
    honeypot: Optional[StrictInt] = 0
    renounced: Optional[StrictInt] = 0
    can_sell: Optional[StrictInt] = 0
    can_not_sell: Optional[StrictInt] = 0
    buy_tax: Optional[StrictStr] = ''
    sell_tax: Optional[StrictStr] = ''
    average_tax: Optional[StrictStr] = ''
    high_tax: Optional[StrictStr] = ''
    flags: Optional[List[StrictStr]] = None
    lock_summary: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["is_show_alert", "top_10_holder_rate", "renounced_mint", "renounced_freeze_account", "burn_ratio", "burn_status", "dev_token_burn_amount", "dev_token_burn_ratio", "open_source", "blacklist", "honeypot", "renounced", "can_sell", "can_not_sell", "buy_tax", "sell_tax", "average_tax", "high_tax", "flags", "lock_summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecurityInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if lock_summary (nullable) is None
        # and model_fields_set contains the field
        if self.lock_summary is None and "lock_summary" in self.model_fields_set:
            _dict['lock_summary'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecurityInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_show_alert": obj.get("is_show_alert") if obj.get("is_show_alert") is not None else False,
            "top_10_holder_rate": obj.get("top_10_holder_rate") if obj.get("top_10_holder_rate") is not None else '',
            "renounced_mint": obj.get("renounced_mint") if obj.get("renounced_mint") is not None else False,
            "renounced_freeze_account": obj.get("renounced_freeze_account") if obj.get("renounced_freeze_account") is not None else False,
            "burn_ratio": obj.get("burn_ratio") if obj.get("burn_ratio") is not None else '',
            "burn_status": obj.get("burn_status") if obj.get("burn_status") is not None else '',
            "dev_token_burn_amount": obj.get("dev_token_burn_amount") if obj.get("dev_token_burn_amount") is not None else '',
            "dev_token_burn_ratio": obj.get("dev_token_burn_ratio") if obj.get("dev_token_burn_ratio") is not None else '',
            "open_source": obj.get("open_source") if obj.get("open_source") is not None else 0,
            "blacklist": obj.get("blacklist") if obj.get("blacklist") is not None else 0,
            "honeypot": obj.get("honeypot") if obj.get("honeypot") is not None else 0,
            "renounced": obj.get("renounced") if obj.get("renounced") is not None else 0,
            "can_sell": obj.get("can_sell") if obj.get("can_sell") is not None else 0,
            "can_not_sell": obj.get("can_not_sell") if obj.get("can_not_sell") is not None else 0,
            "buy_tax": obj.get("buy_tax") if obj.get("buy_tax") is not None else '',
            "sell_tax": obj.get("sell_tax") if obj.get("sell_tax") is not None else '',
            "average_tax": obj.get("average_tax") if obj.get("average_tax") is not None else '',
            "high_tax": obj.get("high_tax") if obj.get("high_tax") is not None else '',
            "flags": obj.get("flags"),
            "lock_summary": obj.get("lock_summary")
        })
        return _obj


