# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SmartMoneyInfo(BaseModel):
    """
    SmartMoneyInfo
    """ # noqa: E501
    address: Optional[StrictStr] = ''
    twitter_username: Optional[StrictStr] = None
    twitter_name: Optional[StrictStr] = None
    total_value: Optional[Union[StrictFloat, StrictInt]] = 0.0
    realized_profit: Optional[Union[StrictFloat, StrictInt]] = 0.0
    unrealized_profit: Optional[Union[StrictFloat, StrictInt]] = 0.0
    pnl: Optional[Union[StrictFloat, StrictInt]] = 0.0
    winrate: Optional[Union[StrictFloat, StrictInt]] = None
    buy_7d: Optional[StrictInt] = 0
    sell_7d: Optional[StrictInt] = 0
    buy_30d: Optional[StrictInt] = 0
    sell_30d: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["address", "twitter_username", "twitter_name", "total_value", "realized_profit", "unrealized_profit", "pnl", "winrate", "buy_7d", "sell_7d", "buy_30d", "sell_30d"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SmartMoneyInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if twitter_username (nullable) is None
        # and model_fields_set contains the field
        if self.twitter_username is None and "twitter_username" in self.model_fields_set:
            _dict['twitter_username'] = None

        # set to None if twitter_name (nullable) is None
        # and model_fields_set contains the field
        if self.twitter_name is None and "twitter_name" in self.model_fields_set:
            _dict['twitter_name'] = None

        # set to None if winrate (nullable) is None
        # and model_fields_set contains the field
        if self.winrate is None and "winrate" in self.model_fields_set:
            _dict['winrate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SmartMoneyInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address") if obj.get("address") is not None else '',
            "twitter_username": obj.get("twitter_username"),
            "twitter_name": obj.get("twitter_name"),
            "total_value": obj.get("total_value") if obj.get("total_value") is not None else 0.0,
            "realized_profit": obj.get("realized_profit") if obj.get("realized_profit") is not None else 0.0,
            "unrealized_profit": obj.get("unrealized_profit") if obj.get("unrealized_profit") is not None else 0.0,
            "pnl": obj.get("pnl") if obj.get("pnl") is not None else 0.0,
            "winrate": obj.get("winrate"),
            "buy_7d": obj.get("buy_7d") if obj.get("buy_7d") is not None else 0,
            "sell_7d": obj.get("sell_7d") if obj.get("sell_7d") is not None else 0,
            "buy_30d": obj.get("buy_30d") if obj.get("buy_30d") is not None else 0,
            "sell_30d": obj.get("sell_30d") if obj.get("sell_30d") is not None else 0
        })
        return _obj


