# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SocialMentionInfo(BaseModel):
    """
    SocialMentionInfo
    """ # noqa: E501
    post_id: Optional[StrictStr] = ''
    platform: Optional[StrictInt] = 0
    post_type: Optional[StrictStr] = ''
    post_timestamp: Optional[StrictInt] = 0
    screen_name: Optional[StrictStr] = ''
    user_name: Optional[StrictStr] = ''
    avatar: Optional[StrictStr] = ''
    content_text: Optional[StrictStr] = ''
    like_count: Optional[StrictInt] = 0
    retweet_count: Optional[StrictInt] = 0
    comment_count: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["post_id", "platform", "post_type", "post_timestamp", "screen_name", "user_name", "avatar", "content_text", "like_count", "retweet_count", "comment_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SocialMentionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SocialMentionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "post_id": obj.get("post_id") if obj.get("post_id") is not None else '',
            "platform": obj.get("platform") if obj.get("platform") is not None else 0,
            "post_type": obj.get("post_type") if obj.get("post_type") is not None else '',
            "post_timestamp": obj.get("post_timestamp") if obj.get("post_timestamp") is not None else 0,
            "screen_name": obj.get("screen_name") if obj.get("screen_name") is not None else '',
            "user_name": obj.get("user_name") if obj.get("user_name") is not None else '',
            "avatar": obj.get("avatar") if obj.get("avatar") is not None else '',
            "content_text": obj.get("content_text") if obj.get("content_text") is not None else '',
            "like_count": obj.get("like_count") if obj.get("like_count") is not None else 0,
            "retweet_count": obj.get("retweet_count") if obj.get("retweet_count") is not None else 0,
            "comment_count": obj.get("comment_count") if obj.get("comment_count") is not None else 0
        })
        return _obj


