# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TokenDetail(BaseModel):
    """
    TokenDetail
    """ # noqa: E501
    chain: Optional[StrictStr] = 'sol'
    address: Optional[StrictStr] = ''
    symbol: Optional[StrictStr] = ''
    name: Optional[StrictStr] = ''
    logo: Optional[StrictStr] = ''
    total_supply: Optional[StrictInt] = 0
    decimals: Optional[StrictInt] = 6
    creation_timestamp: Optional[StrictInt] = 0
    migrated_timestamp: Optional[StrictInt] = 0
    biggest_pool_address: Optional[StrictStr] = ''
    pool_address: Optional[StrictStr] = None
    quote_address: Optional[StrictStr] = None
    exchange: Optional[StrictStr] = None
    pool_type: Optional[StrictStr] = None
    launch_type: Optional[StrictStr] = None
    standard: Optional[StrictStr] = '2022'
    launchpad: Optional[StrictStr] = None
    launchpad_progress: Optional[StrictInt] = None
    launchpad_status: Optional[StrictInt] = None
    launchpad_platform: Optional[StrictStr] = None
    migration_market_cap: Optional[Union[StrictFloat, StrictInt]] = None
    migration_market_cap_quote: Optional[StrictStr] = None
    creator_address: Optional[StrictStr] = ''
    holder_count: Optional[StrictInt] = 0
    liquidity: Optional[Union[StrictFloat, StrictInt]] = 0.0
    __properties: ClassVar[List[str]] = ["chain", "address", "symbol", "name", "logo", "total_supply", "decimals", "creation_timestamp", "migrated_timestamp", "biggest_pool_address", "pool_address", "quote_address", "exchange", "pool_type", "launch_type", "standard", "launchpad", "launchpad_progress", "launchpad_status", "launchpad_platform", "migration_market_cap", "migration_market_cap_quote", "creator_address", "holder_count", "liquidity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pool_address (nullable) is None
        # and model_fields_set contains the field
        if self.pool_address is None and "pool_address" in self.model_fields_set:
            _dict['pool_address'] = None

        # set to None if quote_address (nullable) is None
        # and model_fields_set contains the field
        if self.quote_address is None and "quote_address" in self.model_fields_set:
            _dict['quote_address'] = None

        # set to None if exchange (nullable) is None
        # and model_fields_set contains the field
        if self.exchange is None and "exchange" in self.model_fields_set:
            _dict['exchange'] = None

        # set to None if pool_type (nullable) is None
        # and model_fields_set contains the field
        if self.pool_type is None and "pool_type" in self.model_fields_set:
            _dict['pool_type'] = None

        # set to None if launch_type (nullable) is None
        # and model_fields_set contains the field
        if self.launch_type is None and "launch_type" in self.model_fields_set:
            _dict['launch_type'] = None

        # set to None if launchpad (nullable) is None
        # and model_fields_set contains the field
        if self.launchpad is None and "launchpad" in self.model_fields_set:
            _dict['launchpad'] = None

        # set to None if launchpad_progress (nullable) is None
        # and model_fields_set contains the field
        if self.launchpad_progress is None and "launchpad_progress" in self.model_fields_set:
            _dict['launchpad_progress'] = None

        # set to None if launchpad_status (nullable) is None
        # and model_fields_set contains the field
        if self.launchpad_status is None and "launchpad_status" in self.model_fields_set:
            _dict['launchpad_status'] = None

        # set to None if launchpad_platform (nullable) is None
        # and model_fields_set contains the field
        if self.launchpad_platform is None and "launchpad_platform" in self.model_fields_set:
            _dict['launchpad_platform'] = None

        # set to None if migration_market_cap (nullable) is None
        # and model_fields_set contains the field
        if self.migration_market_cap is None and "migration_market_cap" in self.model_fields_set:
            _dict['migration_market_cap'] = None

        # set to None if migration_market_cap_quote (nullable) is None
        # and model_fields_set contains the field
        if self.migration_market_cap_quote is None and "migration_market_cap_quote" in self.model_fields_set:
            _dict['migration_market_cap_quote'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chain": obj.get("chain") if obj.get("chain") is not None else 'sol',
            "address": obj.get("address") if obj.get("address") is not None else '',
            "symbol": obj.get("symbol") if obj.get("symbol") is not None else '',
            "name": obj.get("name") if obj.get("name") is not None else '',
            "logo": obj.get("logo") if obj.get("logo") is not None else '',
            "total_supply": obj.get("total_supply") if obj.get("total_supply") is not None else 0,
            "decimals": obj.get("decimals") if obj.get("decimals") is not None else 6,
            "creation_timestamp": obj.get("creation_timestamp") if obj.get("creation_timestamp") is not None else 0,
            "migrated_timestamp": obj.get("migrated_timestamp") if obj.get("migrated_timestamp") is not None else 0,
            "biggest_pool_address": obj.get("biggest_pool_address") if obj.get("biggest_pool_address") is not None else '',
            "pool_address": obj.get("pool_address"),
            "quote_address": obj.get("quote_address"),
            "exchange": obj.get("exchange"),
            "pool_type": obj.get("pool_type"),
            "launch_type": obj.get("launch_type"),
            "standard": obj.get("standard") if obj.get("standard") is not None else '2022',
            "launchpad": obj.get("launchpad"),
            "launchpad_progress": obj.get("launchpad_progress"),
            "launchpad_status": obj.get("launchpad_status"),
            "launchpad_platform": obj.get("launchpad_platform"),
            "migration_market_cap": obj.get("migration_market_cap"),
            "migration_market_cap_quote": obj.get("migration_market_cap_quote"),
            "creator_address": obj.get("creator_address") if obj.get("creator_address") is not None else '',
            "holder_count": obj.get("holder_count") if obj.get("holder_count") is not None else 0,
            "liquidity": obj.get("liquidity") if obj.get("liquidity") is not None else 0.0
        })
        return _obj


