# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TokenAnalytics(BaseModel):
    """
    TokenAnalytics
    """ # noqa: E501
    holder_count: Optional[StrictInt] = 0
    bluechip_owner_count: Optional[StrictInt] = 0
    bluechip_owner_percentage: Optional[StrictStr] = ''
    signal_count: Optional[StrictInt] = 0
    degen_call_count: Optional[StrictInt] = 0
    top_rat_trader_percentage: Optional[StrictStr] = ''
    top_bundler_trader_percentage: Optional[StrictStr] = ''
    top_entrapment_trader_percentage: Optional[StrictStr] = ''
    top_bot_degen_percentage: Optional[StrictStr] = ''
    creator_created_count: Optional[StrictInt] = 0
    bot_degen_count: Optional[StrictInt] = 0
    bot_degen_rate: Optional[StrictStr] = ''
    fresh_wallet_rate: Optional[StrictStr] = ''
    top_10_holder_rate: Optional[StrictStr] = ''
    dev_team_hold_rate: Optional[StrictStr] = ''
    creator_hold_rate: Optional[StrictStr] = ''
    creator_token_balance: Optional[StrictStr] = ''
    private_vault_hold_rate: Optional[StrictStr] = ''
    top70_sniper_hold_rate: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["holder_count", "bluechip_owner_count", "bluechip_owner_percentage", "signal_count", "degen_call_count", "top_rat_trader_percentage", "top_bundler_trader_percentage", "top_entrapment_trader_percentage", "top_bot_degen_percentage", "creator_created_count", "bot_degen_count", "bot_degen_rate", "fresh_wallet_rate", "top_10_holder_rate", "dev_team_hold_rate", "creator_hold_rate", "creator_token_balance", "private_vault_hold_rate", "top70_sniper_hold_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenAnalytics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenAnalytics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "holder_count": obj.get("holder_count") if obj.get("holder_count") is not None else 0,
            "bluechip_owner_count": obj.get("bluechip_owner_count") if obj.get("bluechip_owner_count") is not None else 0,
            "bluechip_owner_percentage": obj.get("bluechip_owner_percentage") if obj.get("bluechip_owner_percentage") is not None else '',
            "signal_count": obj.get("signal_count") if obj.get("signal_count") is not None else 0,
            "degen_call_count": obj.get("degen_call_count") if obj.get("degen_call_count") is not None else 0,
            "top_rat_trader_percentage": obj.get("top_rat_trader_percentage") if obj.get("top_rat_trader_percentage") is not None else '',
            "top_bundler_trader_percentage": obj.get("top_bundler_trader_percentage") if obj.get("top_bundler_trader_percentage") is not None else '',
            "top_entrapment_trader_percentage": obj.get("top_entrapment_trader_percentage") if obj.get("top_entrapment_trader_percentage") is not None else '',
            "top_bot_degen_percentage": obj.get("top_bot_degen_percentage") if obj.get("top_bot_degen_percentage") is not None else '',
            "creator_created_count": obj.get("creator_created_count") if obj.get("creator_created_count") is not None else 0,
            "bot_degen_count": obj.get("bot_degen_count") if obj.get("bot_degen_count") is not None else 0,
            "bot_degen_rate": obj.get("bot_degen_rate") if obj.get("bot_degen_rate") is not None else '',
            "fresh_wallet_rate": obj.get("fresh_wallet_rate") if obj.get("fresh_wallet_rate") is not None else '',
            "top_10_holder_rate": obj.get("top_10_holder_rate") if obj.get("top_10_holder_rate") is not None else '',
            "dev_team_hold_rate": obj.get("dev_team_hold_rate") if obj.get("dev_team_hold_rate") is not None else '',
            "creator_hold_rate": obj.get("creator_hold_rate") if obj.get("creator_hold_rate") is not None else '',
            "creator_token_balance": obj.get("creator_token_balance") if obj.get("creator_token_balance") is not None else '',
            "private_vault_hold_rate": obj.get("private_vault_hold_rate") if obj.get("private_vault_hold_rate") is not None else '',
            "top70_sniper_hold_rate": obj.get("top70_sniper_hold_rate") if obj.get("top70_sniper_hold_rate") is not None else ''
        })
        return _obj


