# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from crypticorn.dex.client.models.holder_composition import HolderComposition
from crypticorn.dex.client.models.holder_info import HolderInfo
from crypticorn.dex.client.models.kol_info import KolInfo
from crypticorn.dex.client.models.market_cap_candle_info import MarketCapCandleInfo
from crypticorn.dex.client.models.migration_info import MigrationInfo
from crypticorn.dex.client.models.native_transfer_info import NativeTransferInfo
from crypticorn.dex.client.models.pool_fee_info import PoolFeeInfo
from crypticorn.dex.client.models.risk_analysis_info import RiskAnalysisInfo
from crypticorn.dex.client.models.security_info import SecurityInfo
from crypticorn.dex.client.models.smart_money_info import SmartMoneyInfo
from crypticorn.dex.client.models.social_mention_info import SocialMentionInfo
from crypticorn.dex.client.models.token_analytics import TokenAnalytics
from crypticorn.dex.client.models.token_detail import TokenDetail
from crypticorn.dex.client.models.trade_info import TradeInfo
from crypticorn.dex.client.models.vibe_score_info import VibeScoreInfo
from crypticorn.dex.client.models.wallet_composition import WalletComposition
from typing import Optional, Set
from typing_extensions import Self

class TokenIntelligence(BaseModel):
    """
    Full token intelligence data from a single snapshot.
    """ # noqa: E501
    snapshot_id: StrictInt = Field(description="Internal snapshot identifier")
    captured_at: datetime = Field(description="When this data was captured")
    source: StrictStr = Field(description="How data was fetched: 'worker' or 'user_request'")
    token_detail: Optional[TokenDetail] = None
    analytics: Optional[TokenAnalytics] = None
    security: Optional[SecurityInfo] = None
    migration: Optional[MigrationInfo] = None
    holder_composition: Optional[HolderComposition] = None
    wallet_composition: Optional[WalletComposition] = None
    smart_money: Optional[SmartMoneyInfo] = None
    native_transfer: Optional[NativeTransferInfo] = None
    holders: Optional[List[HolderInfo]] = None
    trades: Optional[List[TradeInfo]] = None
    social_mentions: Optional[List[SocialMentionInfo]] = None
    pool_fees: Optional[List[PoolFeeInfo]] = None
    market_cap_candles: Optional[List[MarketCapCandleInfo]] = None
    vibe_score: Optional[VibeScoreInfo] = None
    top_kols: Optional[List[KolInfo]] = None
    risk_analysis: Optional[RiskAnalysisInfo] = None
    __properties: ClassVar[List[str]] = ["snapshot_id", "captured_at", "source", "token_detail", "analytics", "security", "migration", "holder_composition", "wallet_composition", "smart_money", "native_transfer", "holders", "trades", "social_mentions", "pool_fees", "market_cap_candles", "vibe_score", "top_kols", "risk_analysis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenIntelligence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of token_detail
        if self.token_detail:
            _dict['token_detail'] = self.token_detail.to_dict()
        # override the default output from pydantic by calling `to_dict()` of analytics
        if self.analytics:
            _dict['analytics'] = self.analytics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of security
        if self.security:
            _dict['security'] = self.security.to_dict()
        # override the default output from pydantic by calling `to_dict()` of migration
        if self.migration:
            _dict['migration'] = self.migration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of holder_composition
        if self.holder_composition:
            _dict['holder_composition'] = self.holder_composition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wallet_composition
        if self.wallet_composition:
            _dict['wallet_composition'] = self.wallet_composition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of smart_money
        if self.smart_money:
            _dict['smart_money'] = self.smart_money.to_dict()
        # override the default output from pydantic by calling `to_dict()` of native_transfer
        if self.native_transfer:
            _dict['native_transfer'] = self.native_transfer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in holders (list)
        _items = []
        if self.holders:
            for _item_holders in self.holders:
                if _item_holders:
                    _items.append(_item_holders.to_dict())
            _dict['holders'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in trades (list)
        _items = []
        if self.trades:
            for _item_trades in self.trades:
                if _item_trades:
                    _items.append(_item_trades.to_dict())
            _dict['trades'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in social_mentions (list)
        _items = []
        if self.social_mentions:
            for _item_social_mentions in self.social_mentions:
                if _item_social_mentions:
                    _items.append(_item_social_mentions.to_dict())
            _dict['social_mentions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pool_fees (list)
        _items = []
        if self.pool_fees:
            for _item_pool_fees in self.pool_fees:
                if _item_pool_fees:
                    _items.append(_item_pool_fees.to_dict())
            _dict['pool_fees'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in market_cap_candles (list)
        _items = []
        if self.market_cap_candles:
            for _item_market_cap_candles in self.market_cap_candles:
                if _item_market_cap_candles:
                    _items.append(_item_market_cap_candles.to_dict())
            _dict['market_cap_candles'] = _items
        # override the default output from pydantic by calling `to_dict()` of vibe_score
        if self.vibe_score:
            _dict['vibe_score'] = self.vibe_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in top_kols (list)
        _items = []
        if self.top_kols:
            for _item_top_kols in self.top_kols:
                if _item_top_kols:
                    _items.append(_item_top_kols.to_dict())
            _dict['top_kols'] = _items
        # override the default output from pydantic by calling `to_dict()` of risk_analysis
        if self.risk_analysis:
            _dict['risk_analysis'] = self.risk_analysis.to_dict()
        # set to None if token_detail (nullable) is None
        # and model_fields_set contains the field
        if self.token_detail is None and "token_detail" in self.model_fields_set:
            _dict['token_detail'] = None

        # set to None if analytics (nullable) is None
        # and model_fields_set contains the field
        if self.analytics is None and "analytics" in self.model_fields_set:
            _dict['analytics'] = None

        # set to None if security (nullable) is None
        # and model_fields_set contains the field
        if self.security is None and "security" in self.model_fields_set:
            _dict['security'] = None

        # set to None if migration (nullable) is None
        # and model_fields_set contains the field
        if self.migration is None and "migration" in self.model_fields_set:
            _dict['migration'] = None

        # set to None if holder_composition (nullable) is None
        # and model_fields_set contains the field
        if self.holder_composition is None and "holder_composition" in self.model_fields_set:
            _dict['holder_composition'] = None

        # set to None if wallet_composition (nullable) is None
        # and model_fields_set contains the field
        if self.wallet_composition is None and "wallet_composition" in self.model_fields_set:
            _dict['wallet_composition'] = None

        # set to None if smart_money (nullable) is None
        # and model_fields_set contains the field
        if self.smart_money is None and "smart_money" in self.model_fields_set:
            _dict['smart_money'] = None

        # set to None if native_transfer (nullable) is None
        # and model_fields_set contains the field
        if self.native_transfer is None and "native_transfer" in self.model_fields_set:
            _dict['native_transfer'] = None

        # set to None if vibe_score (nullable) is None
        # and model_fields_set contains the field
        if self.vibe_score is None and "vibe_score" in self.model_fields_set:
            _dict['vibe_score'] = None

        # set to None if risk_analysis (nullable) is None
        # and model_fields_set contains the field
        if self.risk_analysis is None and "risk_analysis" in self.model_fields_set:
            _dict['risk_analysis'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenIntelligence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "snapshot_id": obj.get("snapshot_id"),
            "captured_at": obj.get("captured_at"),
            "source": obj.get("source"),
            "token_detail": TokenDetail.from_dict(obj["token_detail"]) if obj.get("token_detail") is not None else None,
            "analytics": TokenAnalytics.from_dict(obj["analytics"]) if obj.get("analytics") is not None else None,
            "security": SecurityInfo.from_dict(obj["security"]) if obj.get("security") is not None else None,
            "migration": MigrationInfo.from_dict(obj["migration"]) if obj.get("migration") is not None else None,
            "holder_composition": HolderComposition.from_dict(obj["holder_composition"]) if obj.get("holder_composition") is not None else None,
            "wallet_composition": WalletComposition.from_dict(obj["wallet_composition"]) if obj.get("wallet_composition") is not None else None,
            "smart_money": SmartMoneyInfo.from_dict(obj["smart_money"]) if obj.get("smart_money") is not None else None,
            "native_transfer": NativeTransferInfo.from_dict(obj["native_transfer"]) if obj.get("native_transfer") is not None else None,
            "holders": [HolderInfo.from_dict(_item) for _item in obj["holders"]] if obj.get("holders") is not None else None,
            "trades": [TradeInfo.from_dict(_item) for _item in obj["trades"]] if obj.get("trades") is not None else None,
            "social_mentions": [SocialMentionInfo.from_dict(_item) for _item in obj["social_mentions"]] if obj.get("social_mentions") is not None else None,
            "pool_fees": [PoolFeeInfo.from_dict(_item) for _item in obj["pool_fees"]] if obj.get("pool_fees") is not None else None,
            "market_cap_candles": [MarketCapCandleInfo.from_dict(_item) for _item in obj["market_cap_candles"]] if obj.get("market_cap_candles") is not None else None,
            "vibe_score": VibeScoreInfo.from_dict(obj["vibe_score"]) if obj.get("vibe_score") is not None else None,
            "top_kols": [KolInfo.from_dict(_item) for _item in obj["top_kols"]] if obj.get("top_kols") is not None else None,
            "risk_analysis": RiskAnalysisInfo.from_dict(obj["risk_analysis"]) if obj.get("risk_analysis") is not None else None
        })
        return _obj


