# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TradeInfo(BaseModel):
    """
    TradeInfo
    """ # noqa: E501
    tx_hash: Optional[StrictStr] = ''
    token_address: Optional[StrictStr] = ''
    maker: Optional[StrictStr] = ''
    maker_name: Optional[StrictStr] = ''
    maker_twitter_username: Optional[StrictStr] = ''
    maker_twitter_name: Optional[StrictStr] = ''
    maker_tags: Optional[List[StrictStr]] = None
    maker_token_tags: Optional[List[StrictStr]] = None
    event: Optional[StrictStr] = ''
    timestamp: Optional[StrictInt] = 0
    base_amount: Optional[StrictStr] = ''
    quote_amount: Optional[StrictStr] = ''
    amount_usd: Optional[StrictStr] = ''
    price_usd: Optional[StrictStr] = ''
    total_trade: Optional[StrictInt] = 0
    balance: Optional[StrictStr] = ''
    history_bought_amount: Optional[StrictStr] = ''
    history_sold_amount: Optional[StrictStr] = ''
    realized_profit: Optional[StrictStr] = ''
    unrealized_profit: Optional[StrictStr] = ''
    is_open_or_close: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["tx_hash", "token_address", "maker", "maker_name", "maker_twitter_username", "maker_twitter_name", "maker_tags", "maker_token_tags", "event", "timestamp", "base_amount", "quote_amount", "amount_usd", "price_usd", "total_trade", "balance", "history_bought_amount", "history_sold_amount", "realized_profit", "unrealized_profit", "is_open_or_close"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradeInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradeInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tx_hash": obj.get("tx_hash") if obj.get("tx_hash") is not None else '',
            "token_address": obj.get("token_address") if obj.get("token_address") is not None else '',
            "maker": obj.get("maker") if obj.get("maker") is not None else '',
            "maker_name": obj.get("maker_name") if obj.get("maker_name") is not None else '',
            "maker_twitter_username": obj.get("maker_twitter_username") if obj.get("maker_twitter_username") is not None else '',
            "maker_twitter_name": obj.get("maker_twitter_name") if obj.get("maker_twitter_name") is not None else '',
            "maker_tags": obj.get("maker_tags"),
            "maker_token_tags": obj.get("maker_token_tags"),
            "event": obj.get("event") if obj.get("event") is not None else '',
            "timestamp": obj.get("timestamp") if obj.get("timestamp") is not None else 0,
            "base_amount": obj.get("base_amount") if obj.get("base_amount") is not None else '',
            "quote_amount": obj.get("quote_amount") if obj.get("quote_amount") is not None else '',
            "amount_usd": obj.get("amount_usd") if obj.get("amount_usd") is not None else '',
            "price_usd": obj.get("price_usd") if obj.get("price_usd") is not None else '',
            "total_trade": obj.get("total_trade") if obj.get("total_trade") is not None else 0,
            "balance": obj.get("balance") if obj.get("balance") is not None else '',
            "history_bought_amount": obj.get("history_bought_amount") if obj.get("history_bought_amount") is not None else '',
            "history_sold_amount": obj.get("history_sold_amount") if obj.get("history_sold_amount") is not None else '',
            "realized_profit": obj.get("realized_profit") if obj.get("realized_profit") is not None else '',
            "unrealized_profit": obj.get("unrealized_profit") if obj.get("unrealized_profit") is not None else '',
            "is_open_or_close": obj.get("is_open_or_close") if obj.get("is_open_or_close") is not None else 0
        })
        return _obj


