# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class VibeScoreInfo(BaseModel):
    """
    VibeScoreInfo
    """ # noqa: E501
    score: Optional[Union[StrictFloat, StrictInt]] = 0.0
    score_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    engagement: Optional[StrictInt] = 0
    engagement_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    impressions: Optional[StrictInt] = 0
    impressions_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    follower_count: Optional[StrictInt] = 0
    follower_count_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    mentions_count: Optional[StrictInt] = 0
    mentions_count_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    mentioned_kol_count: Optional[StrictInt] = 0
    mentioned_kol_count_change_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    __properties: ClassVar[List[str]] = ["score", "score_change_rate", "engagement", "engagement_change_rate", "impressions", "impressions_change_rate", "follower_count", "follower_count_change_rate", "mentions_count", "mentions_count_change_rate", "mentioned_kol_count", "mentioned_kol_count_change_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VibeScoreInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VibeScoreInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "score": obj.get("score") if obj.get("score") is not None else 0.0,
            "score_change_rate": obj.get("score_change_rate") if obj.get("score_change_rate") is not None else 0.0,
            "engagement": obj.get("engagement") if obj.get("engagement") is not None else 0,
            "engagement_change_rate": obj.get("engagement_change_rate") if obj.get("engagement_change_rate") is not None else 0.0,
            "impressions": obj.get("impressions") if obj.get("impressions") is not None else 0,
            "impressions_change_rate": obj.get("impressions_change_rate") if obj.get("impressions_change_rate") is not None else 0.0,
            "follower_count": obj.get("follower_count") if obj.get("follower_count") is not None else 0,
            "follower_count_change_rate": obj.get("follower_count_change_rate") if obj.get("follower_count_change_rate") is not None else 0.0,
            "mentions_count": obj.get("mentions_count") if obj.get("mentions_count") is not None else 0,
            "mentions_count_change_rate": obj.get("mentions_count_change_rate") if obj.get("mentions_count_change_rate") is not None else 0.0,
            "mentioned_kol_count": obj.get("mentioned_kol_count") if obj.get("mentioned_kol_count") is not None else 0,
            "mentioned_kol_count_change_rate": obj.get("mentioned_kol_count_change_rate") if obj.get("mentioned_kol_count_change_rate") is not None else 0.0
        })
        return _obj


