# coding: utf-8

"""
    DEX AI API

    API for DEX AI

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WalletComposition(BaseModel):
    """
    WalletComposition
    """ # noqa: E501
    smart_wallets: Optional[StrictInt] = 0
    fresh_wallets: Optional[StrictInt] = 0
    renowned_wallets: Optional[StrictInt] = 0
    creator_wallets: Optional[StrictInt] = 0
    sniper_wallets: Optional[StrictInt] = 0
    rat_trader_wallets: Optional[StrictInt] = 0
    whale_wallets: Optional[StrictInt] = 0
    top_wallets: Optional[StrictInt] = 0
    following_wallets: Optional[StrictInt] = 0
    bundler_wallets: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["smart_wallets", "fresh_wallets", "renowned_wallets", "creator_wallets", "sniper_wallets", "rat_trader_wallets", "whale_wallets", "top_wallets", "following_wallets", "bundler_wallets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletComposition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletComposition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "smart_wallets": obj.get("smart_wallets") if obj.get("smart_wallets") is not None else 0,
            "fresh_wallets": obj.get("fresh_wallets") if obj.get("fresh_wallets") is not None else 0,
            "renowned_wallets": obj.get("renowned_wallets") if obj.get("renowned_wallets") is not None else 0,
            "creator_wallets": obj.get("creator_wallets") if obj.get("creator_wallets") is not None else 0,
            "sniper_wallets": obj.get("sniper_wallets") if obj.get("sniper_wallets") is not None else 0,
            "rat_trader_wallets": obj.get("rat_trader_wallets") if obj.get("rat_trader_wallets") is not None else 0,
            "whale_wallets": obj.get("whale_wallets") if obj.get("whale_wallets") is not None else 0,
            "top_wallets": obj.get("top_wallets") if obj.get("top_wallets") is not None else 0,
            "following_wallets": obj.get("following_wallets") if obj.get("following_wallets") is not None else 0,
            "bundler_wallets": obj.get("bundler_wallets") if obj.get("bundler_wallets") is not None else 0
        })
        return _obj


